packages:
  - benchmarks
  - examples/*
  - tests/e2e

overrides:
  postcss@<8.5.10: 8.5.17
  srvx@<0.11.13: 0.11.22

packageExtensions:
  babel-plugin-react-compiler@1.0.0:
    dependencies:
      zod: ^4.3.6

allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
  sharp: true

minimumReleaseAge: 0
verifyDepsBeforeRun: false
