packages:
  - benchmarks
  - examples/*
  - tests/e2e

overrides:
  postcss@<8.5.10: 8.5.17
  srvx@<0.11.13: 0.11.22

packageExtensions:
  babel-plugin-react-compiler@1.0.0:
    dependencies:
      zod: ^4.3.6

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true

minimumReleaseAge: 0
verifyDepsBeforeRun: false
